"""create_user_id_column

Revision ID: c7238ae053a0
Revises: 221397ba1545
Create Date: 2026-04-26 09:47:38.954253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7238ae053a0'
down_revision: Union[str, Sequence[str], None] = '221397ba1545'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'person', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'person', type_='foreignkey')
    op.drop_column('person', 'user_id')
    # ### end Alembic commands ###
